/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oies5WSYoq1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"

export function PlayerCards() {
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-gray-900 text-white py-4 px-6 flex items-center justify-between">
        <h1 className="text-2xl font-bold">Trolls FC</h1>
        <Button size="sm" variant="outline">
          <PlusIcon className="h-4 w-4" />
          Add Player
        </Button>
      </header>
      <main className="flex-1 overflow-y-auto p-6">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <Card className="bg-white shadow-md rounded-lg overflow-hidden">
            <div className="flex items-center p-4 border-b">
              <img
                alt="Player Avatar"
                className="rounded-full mr-4"
                height={48}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width={48}
              />
              <div>
                <h2 className="text-lg font-bold">John Doe</h2>
                <p className="text-gray-500">Midfielder</p>
              </div>
            </div>
            <div className="p-4 space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-gray-500">Shooting</span>
                <div className="flex items-center">
                  <button
                    aria-label="Set shooting rating to 1"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set shooting rating to 2"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set shooting rating to 3"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set shooting rating to 4"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set shooting rating to 5"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-500">Passing</span>
                <div className="flex items-center">
                  <button
                    aria-label="Set passing rating to 1"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set passing rating to 2"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set passing rating to 3"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set passing rating to 4"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set passing rating to 5"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-500">Dribbling</span>
                <div className="flex items-center">
                  <button
                    aria-label="Set dribbling rating to 1"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set dribbling rating to 2"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set dribbling rating to 3"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set dribbling rating to 4"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set dribbling rating to 5"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-500">Defending</span>
                <div className="flex items-center">
                  <button
                    aria-label="Set defending rating to 1"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set defending rating to 2"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set defending rating to 3"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set defending rating to 4"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set defending rating to 5"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-500">Overall</span>
                <div className="flex items-center">
                  <button
                    aria-label="Set overall rating to 1"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set overall rating to 2"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set overall rating to 3"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set overall rating to 4"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set overall rating to 5"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                </div>
              </div>
            </div>
          </Card>
          <Card className="bg-white shadow-md rounded-lg overflow-hidden">
            <div className="flex items-center p-4 border-b">
              <img
                alt="Player Avatar"
                className="rounded-full mr-4"
                height={48}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width={48}
              />
              <div>
                <h2 className="text-lg font-bold">Jane Smith</h2>
                <p className="text-gray-500">Forward</p>
              </div>
            </div>
            <div className="p-4 space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-gray-500">Shooting</span>
                <div className="flex items-center">
                  <button
                    aria-label="Set shooting rating to 1"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set shooting rating to 2"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set shooting rating to 3"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set shooting rating to 4"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set shooting rating to 5"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-500">Passing</span>
                <div className="flex items-center">
                  <button
                    aria-label="Set passing rating to 1"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set passing rating to 2"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set passing rating to 3"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set passing rating to 4"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set passing rating to 5"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-500">Dribbling</span>
                <div className="flex items-center">
                  <button
                    aria-label="Set dribbling rating to 1"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set dribbling rating to 2"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set dribbling rating to 3"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set dribbling rating to 4"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set dribbling rating to 5"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-500">Defending</span>
                <div className="flex items-center">
                  <button
                    aria-label="Set defending rating to 1"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set defending rating to 2"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set defending rating to 3"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set defending rating to 4"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                  <button
                    aria-label="Set defending rating to 5"
                    className="text-yellow-500 hover:text-yellow-600 focus:outline-none"
                  >
                    <StarIcon className="h-5 w-5" />
                  </button>
                </div>
              </div>
              <div className="flex items-center justify-between" />
            </div>
          </Card>
        </div>
      </main>
    </div>
  )
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
